name: Update index.txt

on:
  push:
    branches: [main]
    paths:
      - 'media/**'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Regenerate index.txt
        run: |
          find media -maxdepth 1 -type f -printf '%f\n' | sort > index.txt
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain index.txt)" ]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add index.txt
            git commit -m "Update index.txt"
            git push
          fi
